// Core domain models — provider-agnostic. UI must never depend on a specific provider shape.

export interface Song {
  id: string; // local stable id: `${providerId}:${providerTrackId}` or local file hash
  providerId: string;
  providerTrackId: string;
  title: string;
  artist: string;
  artistId?: string;
  album: string;
  albumId?: string;
  durationMs: number;
  /**
   * What the provider actually lets us play — never inferred from duration
   * and never assumed from `streamUrl != null`.
   * - "full": the complete commercial recording (or full-length licensed file)
   * - "preview": a short provider-controlled excerpt
   * Undefined means "unknown / not yet classified" — use isPreviewSong().
   */
  streamType?: StreamType;
  /** True when only a short preview is playable (mirrors capabilities.previewOnly). */
  previewOnly?: boolean;
  /** Actual playable preview length in ms when previewOnly (e.g. ~30000). */
  previewDurationMs?: number;
  artworkUrl?: string;
  artworkLocal?: string; // object URL / cached path
  streamUrl?: string; // resolved at play time via provider.getStream()
  downloadUrl?: string; // provider download endpoint (only when downloadAllowed)
  downloadAllowed?: boolean; // per-track offline permission from the provider/license
  license?: string; // license name/URL reported by the provider
  sourceUrl?: string; // canonical provider page for this track
  genre?: string;
  year?: number;
  trackNo?: number;
  isLocalFile?: boolean;
  localPath?: string;
  isOfflineAvailable?: boolean;
  isFavorite?: boolean;
  playCount?: number;
  lastPlayedAt?: number;
  addedAt: number;
  /** Search-engine relevance (0–100). Attached by src/search/ranking.ts. */
  relevanceScore?: number;
  /** Search-engine match confidence: exact | strong | partial | related. */
  matchType?: 'exact' | 'strong' | 'partial' | 'related';
  /**
   * How this entry entered the playback queue.
   * - "manual": user-queued (default; `undefined` means manual for legacy rows).
   * - "autoplay": generated by KNOX Autoplay / Continuous Play.
   * Manual items always have priority over autoplay items. Autoplay items
   * may be removed/replaced without affecting manual items.
   */
  queueSource?: 'manual' | 'autoplay';
  /** All contributing artists when the provider reports more than one. */
  artists?: string[];
  /** Per-track capabilities. SEARCH ≠ STREAMING ≠ DOWNLOAD ≠ OFFLINE. */
  capabilities?: TrackCapabilities;
}

/** Per-track capabilities — each flag is independent. */
export interface TrackCapabilities {
  searchable: boolean;
  streamable: boolean;
  downloadable: boolean;
  offline: boolean;
  /**
   * True when the streamable URL is only a short preview, NOT the full
   * recording. A preview is never downloadable/offline-capable.
   * Do NOT infer this from duration or from `streamUrl != null`.
   */
  previewOnly: boolean;
}

/** What the provider actually lets us play for a given track. */
export type StreamType = 'full' | 'preview';

export interface Artist {
  id: string;
  providerId: string;
  providerArtistId: string;
  name: string;
  artworkUrl?: string;
  bio?: string;
}

export interface Album {
  id: string;
  providerId: string;
  providerAlbumId: string;
  title: string;
  artist: string;
  artistId?: string;
  year?: number;
  artworkUrl?: string;
  trackCount?: number;
}

export interface Playlist {
  id: string;
  name: string;
  description?: string;
  coverUrl?: string;
  createdAt: number;
  updatedAt: number;
  trackIds: string[]; // ordered Song ids
  isUserPlaylist: boolean;
  providerId?: string;
  providerPlaylistId?: string;
}

export interface HistoryEntry {
  id: string;
  songId: string;
  title: string;
  artist: string;
  playedAt: number;
  durationListenedMs: number;
}

export interface LyricLine {
  timeMs: number;
  text: string;
}

export interface Lyrics {
  songId: string;
  lines: LyricLine[];
  synced: boolean;
  source: string;
}

export interface SearchResults {
  songs: Song[];
  artists: Artist[];
  albums: Album[];
  playlists: Playlist[];
}
